### ISSUE TITLE
vault inject and whitelist source for LB

### ISSUE THREAD

**Issue by myvelmurugan** [vertica/vertica-kubernetes#157]
@spilchen 
I need to inject secrets using vault agent. 

In this customresource how can we annotate for the deployment and also need to whitelist some source IP range for the loadbalancer service. 

In documentation, I am not sure how to add specific option for the objects. can you please help us with this.

**Comment by spilchen** [comment]
Closing this until we get more information.

Note, you can now add annotations just for the service objects through the `spec.subclusters[i].serviceAnnotations` CR parameter.  See [our documentation](https://www.vertica.com/docs/latest/HTML/Content/Authoring/Containers/Kubernetes/Operator/CustomResourceDefinitionParams.htm) for more info.
