### ISSUE TITLE
Shutdown during package installation

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#163]
In our product we have to restart the whole vertica cluster because of the internode encryption: https://www.vertica.com/docs/11.0.x/HTML/Content/Authoring/Security/TLS/ControlChannelSpreadTLS.htm?tocpath=Security%20and%20Authentication%7CInternode%20TLS%7C_____1

It is implemented in our vertica container to call `admintools --tool stop_db -d <db-name>` after the necessary steps with `--force` and `--noprompts` flags.

>Note: we wait to get a ready db status before we call the stop_db  (with `admintools --tool db_status --s UP` command)

There are two strange things:
- DB status is `up` (based on the output of the `admintools --tool db_status`) independently from the status of the default installed packages (`admintools -t list_packages --package default -d <db-name>`)
- It seems to us, that the shutdown process waits for the package installtion, and takes a long time to shutdown the cluster if the vertica default package installation is not finished yet.

Sometimes it takes 10 minutes to "get back the prompt" after the  `admintools --tool stop_db` command, so it seems to us, that we have to check the status of the installed packages or we should pull the state from the CR.

Maybe the pull state solution would be the good solution, because the operator somehow shows `UP` state after all default Vertica packages are installed.

To be able to check the state from the Vertica container we have to get serviceaccount option for the Vertica container in the generated statefulset.

I know... it is not a good direction, but we have to restart the Vertica because of this internode tls limitation of the Vertica.

**Comment by spilchen** [comment]
I assume since you are talking about waiting for package installation that you are doing this around the time the database is being created?  If so, there is a check you can use to wait until the create database has finished installing all of the packages.  This command will synchronously wait:

```
kubectl wait --for=condition=DBInitialized vdb <vdb-name> --timeout=900s
```

**Comment by nyikesda** [comment]
Sorry about I not closed it earlier. Thanks for the answer.
As far as I know you opened an internal ticket about the required server restart to make it possible to turn on internode encryption without restarting
