### ISSUE TITLE
Readyprobe is too strict

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#192]
The generated statefulset contains a very strict readyprobe for the Vertica container, because of the 1s timeout for the vsql  -c 'select 1' command, so it causes many false negative readyprobe failure.
It should be higher or it should be a configurable parameter to avoid readyprobe failure if the response time is a bit higher in the Vertica

**Comment by spilchen** [comment]
What is the concern if the ready probe fails?  You need to have 3 consecutive failures before the ready state turns off.  And this would affect routing decisions through the service object.  Did you see high load on the pod when it got into this state?  If so, is it bad if the client traffic temporarily avoids the pod?

**Comment by nyikesda** [comment]
You are right @spilchen, that it is a good behaviour to avoid more load on a pod, if the vertica response time is high for a simple 'select 1' request. My problem that it is not a well defined wat is high, maybe 1s is high in case of a DB. 
On the other hand it is turned out that there was a dimensioning problem during our tests, and now the vertica response time is about 0m0.064s for the 'select 1' request, so I close the ticket, and thanks for your support.
