### ISSUE TITLE
AWS IRSA auth for S3 communal storage

### ISSUE THREAD

**Issue by harisokanovic** [vertica/vertica-kubernetes#200]
We run Vertica Eon on Amazon's EKS Kubernetes service with S3 for communal storage. We would like to replace our accesskey/secretkey communal credential with a role-based authentication scheme.

EKS provides a mechanism called IRSA (IAM Roles for Service Accounts) to bind IAM roles to K8s service accounts. When configured, a token file (AWS_WEB_IDENTITY_TOKEN_FILE env var) is injected into affected Pods, which clients may redeem for access to service like S3 (or whatever is granted by the IAM role).

Can we configure Vertica Eon to use AWS_WEB_IDENTITY_TOKEN_FILE for authentication instead of a static accesskey/secretkey?

Documentation:
https://eksctl.io/usage/iamserviceaccounts/
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

Thanks,
Haris Okanovic
https://www.ni.com/
https://www.optimalplus.com/

**Comment by spilchen** [comment]
All of the things needed on the operator side are in place to support this. A change was needed in the Vertica server to support this. So, I will keep this open until that server change is generally available.

**Comment by spilchen** [comment]
Vertica server 12.0.3 is out now. So, you can now officially use AWS IRSA. More details on how to set this up are in the Vertica docs:
https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/Containers/Kubernetes/CommunalStorageK8s.htm
