### ISSUE TITLE
Depot volume is not expanded when local.requestSize is changed

### ISSUE THREAD

**Issue by vyaslav** [vertica/vertica-kubernetes#231]
In production we are often required to expand depot volume for already existing and running vertica database. 
Since Depot pvc is managed by statefulset created by vertica operator, we tried to expand it by increasing `local.requestSize`.
This didn't work:
```
2022-07-12T07:41:18.503Z	INFO	controllers.VerticaDB	aborting reconcile of VerticaDB	{"verticadb": "vertica/vertica-cel-1", "result": {"Requeue":false,"RequeueAfter":0}, "err": "StatefulSet.apps \"vertica-cel-1-defaultsubcluster\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}
```
Since depot pvc and statefulset are managed by vertica operator, it should provide a way of expanding depot size to remediate issues like this:
```
Volume [/depot/celonis/v_celonis_node0001_depot] has insufficient space
```

**Comment by vyaslav** [comment]
thanks for the detailed answer @spilchen
Unfortunately patching PVC manually is not a good option for us as we follow gitops.
We would also need to change PVC template in STS and requestSize anyways so in the event of upscale or creating new subclusters we also have an adequate new PVC size.

Also expanding PVC for depot w/o updating storage location has no effect unless its size is recalculated with `alter_location` AFAIK. It would be also great if operator could handle it automatically.

**Comment by spilchen** [comment]
Thanks, this is the context I was looking for.
