### ISSUE TITLE
Subcluster Monitoring

### ISSUE THREAD

**Issue by Jmoore1127** [vertica/vertica-kubernetes#256]
After deploying the operator locally and testing with prometheus I was surprised to find that the metrics available are largely related to the operator itself and not the (sub)cluster pods that are created from the VerticaDB CR. 

I am looking for metrics regarding cluster performance, bottle-necking, etc. that would normally be available in the MC for a non-k8s deployment of vertica. Are these available somewhere?

**Comment by spilchen** [comment]
No, they are not yet available.  This is something that we are actively working on.  We are hoping to have a release next year that will export the metrics that you are after.

**Comment by Jmoore1127** [comment]
Is there anyway to get them manually? I am not sure how vertica exposes stats in general. This would be a blocker to us being able to use this until those are released

**Comment by spilchen** [comment]
Vertica has a lot of monitoring information.  It can all be accessed through SQL.  See the docs for all of the tables/views that we have:
https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/SQLReferenceManual/SystemTables/MONITOR/V_MONITORSchema.htm

If you intend to use Prometheus, there are exporters that will issue SQL and convert them to a format suitable for Prometheus.  

This one in particular is general purpose and recently had Vertica support added to it:
https://github.com/burningalchemist/sql_exporter

This one has some pre-canned metrics for Vertica.  But I've never used it, so I don't know how valuable they are for monitoring your database.  
https://github.com/blacksponge/vertica-prometheus-exporter

**Comment by Jmoore1127** [comment]
Thanks, I'll look into those. Looking forward to the upcoming releases.
