### ISSUE TITLE
Vertica running (in cluster) on GKE failed to install Vertica Extension packages

### ISSUE THREAD

**Issue by danieleharel** [vertica/vertica-kubernetes#383]
Facing an issue installing vertica packages
Running:
admintools -t install_package -d **** -p **** --package default

Receiving some errors:
Checking whether package VFunctions is already installed...
Package VFunctions is already installed
Checking whether package flextable is already installed...
Installing package flextable...
Failed to install package flextable
Checking whether package DelimitedExport is already installed...
Package DelimitedExport is already installed
Checking whether package JsonExport is already installed...
Package JsonExport is already installed
Checking whether package kafka is already installed...
Installing package kafka...
Failed to install package kafka
Checking whether package approximate is already installed...
Package approximate is already installed
Checking whether package ComplexTypes is already installed...
Package ComplexTypes is already installed
Checking whether package OrcExport is already installed...
Installing package OrcExport...
Failed to install package OrcExport
Checking whether package place is already installed...
Installing package place...
Failed to install package place
Checking whether package txtindex is already installed...
Package txtindex is already installed
Checking whether package voltagesecure is already installed...
Installing package voltagesecure...
Failed to install package voltagesecure
Checking whether package ParquetExport is already installed...
Installing package ParquetExport...
Failed to install package ParquetExport
Checking whether package MachineLearning is already installed...
Installing package MachineLearning...
Failed to install package MachineLearning
Checking whether package logsearch is already installed...
Installing package logsearch...
Failed to install package logsearch

I opened all these ports: 
TCP/SSH 22
TCP/UDP 4803
TCP/UDP 5433
UDP 4804
TCP 5434
UDP 6543

as mentioned here:
https://knowledge.broadcom.com/external/article/94764/dr-installation-failed-to-install-vertic.html

Any ideas?
Thanks

**Comment by spilchen** [comment]
What image are you using? Is there a particular package that you are looking for?

**Comment by danieleharel** [comment]
vertica/vertica-k8s:12.0.2-0

flextable is one of the packages i need.

**Comment by danieleharel** [comment]
I just saw this that some of the commands with admintools don't support GCP.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/109030480/233837860-a0463a0d-fb3f-4da7-835b-017727c96081.png">

**Comment by spilchen** [comment]
We support the operator on GCP...

flextable should already be installed. You don't need to install that package manually. It would have been installed when you created the database. Do you still have the operator logs from when create db was done? 

`kubectl logs --selector control-plane=controller-manager --container manager` 

If you do have these logs, you should see from the create db command the packages that were installed, and flextable should be one of them.

**Comment by spilchen** [comment]
Please reopen if you have the operator logs showing the create database didn't install flextable.
