### ISSUE TITLE
Do not validate the autoRestartVertica during image upgrade

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#52]
Based on the actual documentation the image can only changed when autoRestartVertica is false.
As far as I know, the main reason behind this limitation to avoid automatic vertica version increase.
It is not the best, beceause many times a new version from an image only contains other fixes, or features and not the version increase of the vertica rpm.
I think it is enough to highlight in the documentation that vertica db upgrade is not supported, and I would like to recommend to do not block other image version increases (versions which are not contain new vertica db version).

**Comment by spilchen** [comment]
In #51 we are relaxing this restriction.  In that PR, you will be able to change the image name without having to change autoRestartVertica.  The operator will detect when the image changes and will bring down the entire cluster, updates the image in the statefulsets, then restart the cluster.  Does this satisfy your requirement?

**Comment by nyikesda** [comment]
Absolutely. Thanks.
