### ISSUE TITLE
Use the new create db option to configure spread channel

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#535]
In the Vertica 23.3.0-0 release a new feature is introduced which can help to configure spread channel without DB restart.

Vertica documentation about it: https://docs.vertica.com/23.3.x/en/security-and-authentication/internode-tls/control-channel-spread-tls/

Spread encryption configuration is introduced in https://github.com/vertica/vertica-kubernetes/pull/224 into the Operator.

It would be nice to use this new feature and configure spread encryption in create_db step and skip restart.

Could you put this on your roadmap?

**Comment by spilchen** [comment]
Good timing! I am currently working on this. It will be part of the next release of the operator, which is tentatively scheduled for January 2024.
