### ISSUE TITLE
Clarification on CRD docs for httpServerMode

### ISSUE THREAD

**Issue by frankgrimes97** [vertica/vertica-kubernetes#587]
Hi,

The latest docs at https://docs.vertica.com/23.4.x/en/containerized/custom-resource-definition-parameters seem to indicate that the Vertica database node's metric endpoint would be available over HTTP when `httpServerMode` is set to `Enabled` the Prometheus metrics would be available at `http://node-host-name:8443/v1/metrics` by default and that enforcing HTTPS is optional and requires separate configuration:

> To enforce HTTPS, you must alter the TLS configuration with custom certificates.

However, we're seeing that it still seems to get started/deployed using HTTPS and mTLS.
Is the documentation incorrect or out-of-date? Or are we missing some other setting(s) to get the Vertica database node's metrics server to listen and accept connections over plain HTTP in a similar way to what the VerticaDB Operator supports through the following settings?

```
prometheus:
  createServiceMonitor: true
  expose: EnableWithoutAuth
  createProxyRBAC: false
```

Thanks!

**Comment by spilchen** [comment]
I apologize for any confusion. The documentation should be updated to reflect the fact that there is no way to access Vertica server metrics via HTTP. All access must be made via HTTPS.

The documentation was trying to say that if you want to control the TLS configuration, such as setting which certificate is used, you must do so by modifying the Vertica catalog with DDL statements, such as CREATE KEY, CREATE CERTIFICATE, ALTER TLS, and so on.
