### ISSUE TITLE
1 operator multiple verticadb deployments

### ISSUE THREAD

**Issue by PetruGarstea** [vertica/vertica-kubernetes#805]
Hi,
does verticadb-operator-2.1.2 support multiple verticaDB deployments ?
For instance the operator is deployed in a dedicated namespace and the verticadb CR in another namespace.
In this scenario the webhook is trying to reach out the operator svc in CR namespace and that is wrong

`Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "meventtrigger.kb.io": failed to call webhook: Post "https://verticadb-operator-webhook-service.${CR_NAMESPACE}.svc:443/mutate-vertica-com-v1beta1-eventtrigger?timeout=10s": service "verticadb-operator-webhook-service" not found
`
I also tried to find whether any parameters related to the above issue can be addressed in CR doc https://docs.vertica.com/24.1.x/en/containerized/custom-resource-definition-parameters/

Please advise

**Comment by PetruGarstea** [comment]
@spilchen 
Much appreciated to your reply.

Just to be sure in the scenario I described(namespace scoped deployments) the documentation describes:
1. the operator controller has to be deployed in one namespace without operators webhook
2. the operators webhook has to be deployed in each vertica namespace without operator controller 

is that correct ?

**Comment by spilchen** [comment]
Actually, it works the other way around. You only need to deploy the operator webhook once, and it will cover all namespaces. However, you'll need to deploy the operator controller separately, placing one in each namespace where you plan to use Vertica's CRs.
