### ISSUE TITLE
Openshift support

### ISSUE THREAD

**Issue by vyaslav** [vertica/vertica-kubernetes#81]
Currently, the operator can be deployed only in Kubernetes clusters.
But the support of Openshift by vertica operator is essential for companies that use Openshift exclusively.

**Comment by spilchen** [comment]
Spreading this over many PR:
https://github.com/vertica/vertica-kubernetes/pull/96
https://github.com/vertica/vertica-kubernetes/pull/98

**Comment by spilchen** [comment]
https://github.com/vertica/vertica-kubernetes/pull/102
https://github.com/vertica/vertica-kubernetes/pull/111

**Comment by spilchen** [comment]
https://github.com/vertica/vertica-kubernetes/pull/115

**Comment by spilchen** [comment]
https://github.com/vertica/vertica-kubernetes/pull/124

**Comment by spilchen** [comment]
https://github.com/vertica/vertica-kubernetes/pull/129

**Comment by spilchen** [comment]
#139
