### ISSUE TITLE
How to integrate the HDFS as a Communal storage of Verticadb, I have not found the exact documentation of this?

### ISSUE THREAD

**Issue by saibattula93** [vertica/vertica-kubernetes#930]
how to integrate Hadoop Distributed File System (HDFS) as communal storage for VerticaDB, given that specific documentation for this integration seems unavailable. It highlights the need for a clear and concise method or instructions to set up HDFS as the communal storage system in a VerticaDB environment.

**Comment by qindotguan** [comment]
Have you tried the steps using Hadoop file storage as communal storage here? https://docs.vertica.com/latest/en/containerized/configuring-communal-storage/#hadoop-file-storage

Please let me know if you encounter any issues.

**Comment by saibattula93** [comment]
I am following this process:

Step-by-Step Process to Integrate HDFS as Communal Storage with Vertica

Step 1: Download `core-site.xml` and `hdfs-site.xml` from Ambari**

1. Access Ambari Dashboard:
   - Open your browser and log into the Ambari Dashboard.
   
2. Navigate to HDFS Configuration:
   - Once logged in, click on HDFS from the services list on the left side of the dashboard.
   - Then, go to the Configs tab in the HDFS section.

3. Download Configuration Files:
   - In the Configs tab, locate and download the following configuration files:
     - `core-site.xml`
     - `hdfs-site.xml`
   - Save these files locally, as you will need them for the following steps.

Step 2: Create a Kubernetes ConfigMap for Hadoop Configuration


Create the ConfigMap from `core-site.xml` and `hdfs-site.xml`:
   Use the following `kubectl` command to create a ConfigMap in the `vertica` namespace.
   ```bash
   kubectl create configmap hadoop-config --from-file=core-site.xml --from-file=hdfs-site.xml -n vertica
   ```
   - This will create a ConfigMap named `hadoop-config` that stores both `core-site.xml` and `hdfs-site.xml` in the `vertica` namespace.

Verify ConfigMap Creation:
   Run the following command to ensure the ConfigMap has been created successfully:
   ```bash
   kubectl get configmap hadoop-config -n vertica
   ```

Step 3: Modify the Vertica Custom Resource (CR) File

1. Open the Vertica Custom Resource (CR) YAML file:
   Locate and edit the YAML file defining the Vertica deployment. This file will include the communal storage configuration using HDFS.

2. Update the `communal` section:
   In the `communal` section, specify the HDFS path using the `webhdfs://` protocol. Update the path to point to the HDFS NameNode or External IP address, and set the communal storage directory (e.g., `/tmp/data`).

   Here's an example of what the relevant section of your Vertica CR file should look like:

   ```yaml
   apiVersion: vertica.com/v1
   kind: VerticaDB
   metadata:
     name: verticadb
     namespace: vertica
   spec:
     communal:
       path: "webhdfs://External IP>:50070/tmp/data" 
     hadoopConfig:
       configMapName: hadoop-config  
     subclusters:
       - name: sc1
         size: 3
   ```


4. Save the YAML file:
   After editing, save the file as `vertica-cr.yaml`.

Step 4: Deploy Vertica with HDFS as Communal Storage

1. Deploy Vertica using the updated CR file:
   Run the following command to deploy Vertica using the modified CR file:
   ```bash
   kubectl apply -f vertica-cr.yaml
   ```

2. Verify the Deployment:
   You can check the status of the Vertica pods to ensure that the deployment is successful:
   ```bash
   kubectl get pods -n vertica
   ```

3. Check Communal Storage Setup:
   - Once Vertica is running, you can verify that the communal storage is correctly set to HDFS by checking the logs of the Vertica pods.
   - Use the following command to inspect the logs:
     ```bash
     kubectl logs <pod-name> -n vertica
     ```

Step 5: Test HDFS Communal Storage

Verify that Vertica is writing to HDFS:
   After Vertica has been deployed, you should verify that the communal storage is working as expected. Check the `/tmp/data` directory (or the directory you configured in HDFS) to ensure Vertica is storing data there.

Monitor HDFS Usage:
   You can also monitor HDFS usage via the Ambari dashboard or by running HDFS commands to confirm that Vertica is interacting with HDFS properly.

Key Steps

1. Download the `core-site.xml` and `hdfs-site.xml` files from Ambari.
2. Create a Kubernetes ConfigMap to store these Hadoop configurations.
3. Modify the Vertica CR file to reference HDFS as communal storage and use the ConfigMap for Hadoop configurations.
4. Deploy Vertica with the updated configuration.

But i am all the pods are Running, But the READY status is 0/1?

Can you guide me this is right approach or not?

**Comment by qindotguan** [comment]
Thanks for the detailed information. It seems that you define the hadoopConfig in a way that verticadb operator can not recognized:
`strict decoding error: unknown field "spec.hadoopConfig.configMapName"`

Can you update your CR and try again?
```
...
spec:
  hadoopConfig: hadoop-config
```

It would be more helpful if you could provide the verticadb operator (assume it's in verticadb-operator namespace) log related to the webhdfs connection:
```
OPERATOR_NAME=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n verticadb-operator)
kubectl logs $OPERATOR_NAME -n  verticadb-operator | grep webhdfs
```

**Comment by saibattula93** [comment]
Thank you @qindotguan, i resolve the problem
